version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: nayoo-api
    environment:
      MYSQL_ROOT_PASSWORD: nayootestuser1234
      MYSQL_DATABASE: nayootest
      MYSQL_USER: nayootestuser
      MYSQL_PASSWORD: nayootestuser1234
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
